### ISSUE TITLE
Unhelpful Example Sentence

### ISSUE THREAD

**Issue by GameDungeon** [patsytau/anki_german_a1_vocab#1]
Card Id 84886455085 has a really unhelpful example sentence. 
> to be
> 
> I am twenty three.
>
> ---------------------
> sein
> 
> Ich bin dreiundzwanzig.

**Comment by patsytau** [comment]
I'm not sure how the example sentence is unhelpful - since 'bin' is the first-person conjugation of 'sein', the sentence is demonstrating its usage.
