### ISSUE TITLE
Wie schmeckt dir den Salat

### ISSUE THREAD

**Issue by tbm** [patsytau/anki_german_a1_vocab#3]
The README says:

> Replacement: "Wie schmeckt dir der Salat?" -> "Wie schmeckt dir den Salat?" - should be accusative, following feedback from a native German speaker.

I'm a native German speaker and this change seems incorrect to me. My dad agrees.  We speak Austrian German and there are some small differences to Hochdeutch but given the Goethe Institut agrees with us, I'd double check.

(It would be "Magst du DEN Salat"; unfortunately, I can't explain why...)

**Comment by tbm** [comment]
As far as I can tell, the Anki version actually has `der`. So maybe this got fixed already but the README wasn't updated.

**Comment by patsytau** [comment]
Whoops! Thank you for catching this, I'll update the readme.

**Comment by patsytau** [comment]
I've removed the line in the README (commit d88967d6230bdb5faa568fd823889da65f1fd7a3).
