### ISSUE TITLE
Er möchte Sie etwas fragen. Wann kommen Sie? 

### ISSUE THREAD

**Issue by warlockbr** [patsytau/anki_german_a1_vocab#5]
He would like to ask thou something. When are thou coming?

I know the "thou" maybe a little exaggerated, since it's archaic, but it'd be important to highlight the formal tone of the pronoun.

**Comment by tbm** [comment]
I'm just a user, not the creator, but I'm against the use of "thou" since non-native English speakers might not be familiar with it.  I'd just add "polite" or "formal" in brackets.

**Comment by patsytau** [comment]
Thou/thee/thy are sufficiently archaic that I don't think it would be helpful to use them. I'll add some formality indicators though.
