### ISSUE TITLE
Plural forms missing in many cards

### ISSUE THREAD

**Issue by tbm** [patsytau/anki_german_a1_vocab#6]
Some nouns have plural forms, but for many the plural is missing.  Is that intentional?

Also, I'm not sure the way plural forms are expressed is very intuitive, e.g. `der Ehemann, ä, er` or `der Fuß, -ü, e`. Wouldn't it be better to just write `die Ehemänner` / `die Füße`?

**Comment by tbm** [comment]
Examples where the plural is missing: der Anschluss, der Automat, der Bahnhof, ...

**Comment by tbm** [comment]
I just looked at the PDF from Goethe Institut and the problem is there. I'm not sure why they give plurals for some but not all nouns.

It could still be fixed in the Anki deck if you want, though.

**Comment by patsytau** [comment]
Whilst it would be nice to have, since it's not included in the Goethe Institute wordlist I'm inclined to leave this as-is.
