### ISSUE TITLE
Bad example for `Sie`

### ISSUE THREAD

**Issue by tbm** [patsytau/anki_german_a1_vocab#7]
We have this example for `Sie`:

> Wie heißen Sie, bitte?  you (polite)    What is your name, please?

`Sie` means `you` but in the example it's used as `your`, which is not the same in German.

I'm not sure how to solve it.  One option is to give a more literal (and therefore non-idiomatic) English translation (although `What are you called, please` isn't so bad). Another would be to look for a different example sentence.

**Comment by patsytau** [comment]
I took your suggestion of the non-idiomatic English. I think it's the best way. Thank you!
