### ISSUE TITLE
Cosmetic issue? -en/

### ISSUE THREAD

**Issue by tbm** [patsytau/anki_german_a1_vocab#8]
You have:

`die Ehefrau, -en/ `

and

`die Hausfrau, -en/`

and

`der Partner, -/`

I'm not sure what the `/` means here.

 It suggests that there's an alternative plural but since nothing follows the alternative plural is the same as the singular word.  Since that isn't correct, maybe it's just a cosmetic issue and the `/` should be removed?

**Comment by tbm** [comment]
I looked at the Goethe PDF.  This is a stylistic problem introduced in the Anki deck.  The PDF uses `/` to separate male and female forms, but in the Anki deck these are different cards.

**Comment by patsytau** [comment]
Fix is incoming - thank you for spotting this!
