### ISSUE TITLE
He’s coming from Cologne/home now.

### ISSUE THREAD

**Issue by warlockbr** [patsytau/anki_german_a1_vocab#9]
Answer: Er kommt gerade von Köln/von zu Hause.

Why "gerade" and not "jetzt"? Because, as far as I know, "gerade" has the meaning of "straight from", like an adverb of place, not time.

**Comment by warlockbr** [comment]
So " He just came from Cologne " sounds like a more accurate translation.

**Comment by patsytau** [comment]
"He just came from Cologne." would be in the past tense, so I think the card is okay as-is.
